workspace:
  - ./*

client:
  - packages/public/client/*
  - packages/public/client/**/*

editor-renderer:
  - packages/public/editor-renderer/*
  - packages/public/editor-renderer/**/*

legacy-editor-renderer:
  - packages/public/legacy-editor-renderer/*
  - packages/public/legacy-editor-renderer/**/*

notifications-job:
  - packages/public/notifications-job/*
  - packages/public/notifications-job/**/*

server:
  - packages/public/server/*
  - packages/public/server/**/*

server-migrate:
  - packages/migrations/*
  - packages/migrations/**/*

static-assets:
  - packages/public/static-assets/*
  - packages/public/static-assets/**/*

private:
  - packages/private/**/*

ci:
  - .github/*
  - .github/**/*
